### ISSUE TITLE
Punctuation URL encoded in display name

### ISSUE THREAD

**Issue by bamc** [Largo/LastFM2Twitter#4]
![image](https://user-images.githubusercontent.com/884384/33290871-ebafd734-d378-11e7-9298-9db952b833ba.png)

Listening to Cam'ron doesn't look too great as it stands

**Comment by Largo** [comment]
hmm. this might be the twig interfering
try to change the artist and track variable like this: {{artist|raw}} -
{{track|raw}}
If it's that then it's twig. otherwise it's the last.fm api sending us
urlencoded data

2017-11-28 6:44 GMT+09:00 bamc <notifications@github.com>:

**Comment by bamc** [comment]
that does seem to fix it.
